# Generated by Django 5.2.17 on 2026-08-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.SlugField(
                        help_text="Unique within the client, e.g. 'tenant-1'."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shown in the tenant switcher.", max_length=200
                    ),
                ),
                (
                    "ad_group_id",
                    models.CharField(
                        help_text="Azure AD security group object id. Membership grants access to this tenant.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("resource_pool_id", models.CharField(blank=True, max_length=200)),
                ("orchestrator_url", models.URLField(blank=True)),
                (
                    "netbox_site_id",
                    models.IntegerField(
                        blank=True,
                        help_text="NetBox site id this tenant's VLANs are scoped to.",
                        null=True,
                    ),
                ),
                ("azure_subscription_id", models.CharField(blank=True, max_length=64)),
                ("azure_tenant_id", models.CharField(blank=True, max_length=64)),
                ("azure_client_id", models.CharField(blank=True, max_length=64)),
                (
                    "azure_location",
                    models.CharField(
                        blank=True, help_text="e.g. 'eastus'.", max_length=50
                    ),
                ),
                ("azure_subnet_id", models.CharField(blank=True, max_length=300)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenants",
                        to="tenants.client",
                    ),
                ),
            ],
            options={
                "ordering": ["client__name", "name"],
                "unique_together": {("client", "tenant_id")},
            },
        ),
    ]
