# Generated by Django 5.2.17 on 2026-08-27 17:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OnPremRateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vcpu_monthly_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "ram_gb_monthly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="RAM (per GB) monthly rate",
                    ),
                ),
                (
                    "storage_gb_monthly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Storage (per GB) monthly rate",
                    ),
                ),
                (
                    "managed_service_monthly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Flat monthly add-on applied to servers with ServiceDeployment.is_managed set.",
                        max_digits=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "On-prem rate card",
                "verbose_name_plural": "On-prem rate card",
            },
        ),
    ]
