# Generated by Django 5.2.17 on 2026-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("api", "API"),
                            ("template", "Template"),
                            ("resource", "Resource"),
                        ],
                        default="service",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("owner", models.CharField(blank=True, max_length=200)),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Where to actually use/request this, if applicable",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated", max_length=300
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "entries",
                "ordering": ["name"],
            },
        ),
    ]
