# Generated by Django 5.2.17 on 2026-08-27 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_seed_example_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("azure", "Azure"), ("onprem", "On-prem")],
                        max_length=10,
                    ),
                ),
                ("name", models.SlugField(max_length=90)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                            ("deleting", "Deleting"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("external_id", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_groups",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["tenant", "name"],
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="NetworkSecurityGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=90)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                            ("deleting", "Deleting"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("external_id", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nsgs",
                        to="networking.resourcegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "NSG",
                "ordering": ["resource_group", "name"],
                "unique_together": {("resource_group", "name")},
            },
        ),
        migrations.CreateModel(
            name="NsgRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=90)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        help_text="Lower numbers evaluate first, same as Azure NSG rules."
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")], max_length=10
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("tcp", "TCP"), ("udp", "UDP"), ("*", "Any")],
                        max_length=4,
                    ),
                ),
                (
                    "source_address_prefix",
                    models.CharField(default="*", max_length=120),
                ),
                ("source_port_range", models.CharField(default="*", max_length=60)),
                (
                    "destination_address_prefix",
                    models.CharField(default="*", max_length=120),
                ),
                (
                    "destination_port_range",
                    models.CharField(default="*", max_length=60),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                            ("deleting", "Deleting"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nsg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="networking.networksecuritygroup",
                    ),
                ),
            ],
            options={
                "ordering": ["nsg", "priority"],
                "unique_together": {("nsg", "name")},
            },
        ),
        migrations.CreateModel(
            name="ServiceDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=90)),
                (
                    "vm_size",
                    models.CharField(help_text="e.g. 'Standard_B2s'.", max_length=60),
                ),
                ("admin_username", models.CharField(max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                            ("deleting", "Deleting"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("external_id", models.CharField(blank=True, max_length=300)),
                ("console_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nsg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployments",
                        to="networking.networksecuritygroup",
                    ),
                ),
                (
                    "resource_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="networking.resourcegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["resource_group", "name"],
                "unique_together": {("resource_group", "name")},
            },
        ),
        migrations.CreateModel(
            name="Subnet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=90)),
                (
                    "cidr",
                    models.CharField(
                        blank=True,
                        help_text="Populated once provisioning succeeds.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                            ("deleting", "Deleting"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("external_id", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subnets",
                        to="networking.resourcegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["resource_group", "name"],
                "unique_together": {("resource_group", "name")},
            },
        ),
    ]
