# Generated by Django 5.2.17 on 2026-08-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicedeployment",
            name="ram_gb",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="servicedeployment",
            name="storage_gb",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="servicedeployment",
            name="vcpu",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="servicedeployment",
            name="vm_size",
            field=models.CharField(
                help_text="e.g. 'Standard_B2s'. Informational for Azure; on-prem has no VM size catalog to match against.",
                max_length=60,
            ),
        ),
    ]
