# Generated by Django 5.2.17 on 2026-08-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0002_servicedeployment_structured_specs"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicedeployment",
            name="is_managed",
            field=models.BooleanField(
                default=False,
                help_text="Polaris manages this service for the client — adds the on-prem rate card's managed-service cost in Orion. No effect on Azure deployments (Azure managed-service spend, once tracked, will come from Cost Management like everything else).",
            ),
        ),
    ]
