# Generated by Django 5.2.17 on 2026-08-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networking", "0003_servicedeployment_is_managed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networksecuritygroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("failed", "Failed"),
                    ("deleting", "Deleting"),
                    ("gone", "Gone"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="nsgrule",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("failed", "Failed"),
                    ("deleting", "Deleting"),
                    ("gone", "Gone"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="resourcegroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("failed", "Failed"),
                    ("deleting", "Deleting"),
                    ("gone", "Gone"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="servicedeployment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("failed", "Failed"),
                    ("deleting", "Deleting"),
                    ("gone", "Gone"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subnet",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("failed", "Failed"),
                    ("deleting", "Deleting"),
                    ("gone", "Gone"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
